kind: Service
apiVersion: v1
metadata:
  name: assisted-installer-ui
  namespace: '__NAMESPACE__'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      # nodePort: 31000
  selector:
    app: assisted-installer-ui
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: assisted-installer-ui
  namespace: '__NAMESPACE__'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assisted-installer-ui
  template:
    metadata:
      labels:
        app: assisted-installer-ui
    spec:
      containers:
        - name: assisted-installer-ui
          image: __IMAGE__
          imagePullPolicy: Always
          env:
            - name: ASSISTED_SERVICE_URL
              value: '__ASSISTED_SERVICE_URL__'
          ports:
            - containerPort: 80
      restartPolicy: Always
