name: Build and push on merge to selected branches

on:
  push:
    branches:
      - master
      - wizard

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "NODE_OPTIONS=--max-old-space-size=8192" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "REACT_APP_GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "REACT_APP_VERSION=${{ env.GIT_TAG }}" >> $GITHUB_ENV
      - name: Set IMAGE_TAGS env variable
        if: github.ref == 'refs/heads/master'
        run: |
          echo "IMAGE_TAGS=latest,latest-${{ github.sha }},${GITHUB_REF#refs/heads/}-${{ github.sha }}" >> $GITHUB_ENV
      - name: Set IMAGE_TAGS env variable
        if: github.ref != 'refs/heads/master'
        run: |
          echo "IMAGE_TAGS=${{ github.sha }},${GITHUB_REF#refs/heads/}-${{ github.sha }}" >> $GITHUB_ENV
      - name: Read environment variables
        run: |
          echo BRANCH: ${BRANCH}
          echo GIT_TAG: ${GIT_TAG}
          echo IMAGE_TAGS: ${IMAGE_TAGS}
          echo NODE_OPTIONS: ${NODE_OPTIONS}
          echo REACT_APP_GIT_SHA: ${REACT_APP_GIT_SHA}
          echo REACT_APP_VERSION: ${REACT_APP_VERSION}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Node version
        run: |
          echo Node version: `node --version`
      - name: Install dependencies
        run: yarn install
      - name: Call linter
        run: yarn lint
      - name: Build code
        run: yarn build
      - name: Publish to quay.io/edge-infrastructure
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: edge-infrastructure/assisted-installer-ui
          username: ${{ secrets.QUAYIO_EDGE_INFRA_USERNAME }}
          password: ${{ secrets.QUAYIO_EDGE_INFRA_PASSWORD }}
          registry: quay.io
          dockerfile: Dockerfile
          tags: '${{ env.IMAGE_TAGS }}'
