name: Test and build

on: [pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: '^7.18'

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: '^14.6'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
